POST http://localhost:8081/todo-items
Content-Type: application/json

{
  "title": "Buy new TV",
  "description": "Smart TV Sony 234 from Technopolis",
  "scheduleDate": "2025-05-22T00:00:00"
}

###

POST http://localhost:8081/todo-items
Content-Type: application/json

{
  "title": "Stupid Valka",
  "description": null,
  "scheduleDate": "2025-05-22T00:00:00"
}
